# Generated by Django 4.2 on 2023-04-28 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('games_won', models.IntegerField()),
                ('gold', models.IntegerField()),
                ('health', models.IntegerField()),
                ('human', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('health', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('ranged', models.BooleanField()),
                ('flying', models.BooleanField()),
                ('faction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.faction')),
            ],
        ),
    ]
