# Generated by Django 4.2 on 2023-04-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_card_attacked_this_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='attack',
            field=models.IntegerField(default=0),
        ),
    ]
