# Generated by Django 4.2 on 2023-04-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player_attack'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='health_base',
            field=models.IntegerField(default=0),
        ),
    ]
