# Generated by Django 4.2 on 2023-04-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_card_health_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='name',
            field=models.CharField(default='Neutral'),
        ),
    ]
